GMPLAPI4 ; / Problem List API - LIST ;02/27/12  12:00
 ;;TBD;Problem List;;02/27/2012
LIST(RETURN,GMPDFN,GMPSTAT,GMPROV,GMPVIEW,GMPREV,GMPIDX) ;
 ; RETURN - By reference. Array of problems
 ;   RETURN = Total number of problems
 ;   RETURN(0) = No of problems returned (filtered)
 ;   RETURN(I) = Problem data: ifn^problem...
 ; GMPDFN - Patient IFN
 ; GMPSTAT - Status. Any combination of A,I,R (Active,Inactive,Removed). Default=A
 ; GMPREV - 1=Reversed. Default=0
 ; GMPROV - Filter by PROVIDER
 ; GMPVIEW - Filter. S/vamc1/vamc2/.../ or C/...
 ; GMPIDX - Create "B" index. Default=0
 N PLIST
 K RETURN
 S GMPSTAT=$G(GMPSTAT)
 S GMPREV=$G(GMPREV)
 S GMPROV=$G(GMPROV)
 S GMPVIEW=$G(GMPVIEW)
 S GMPIDX=+$G(GMPIDX)
 I '$$GETPLIST(.PLIST,GMPDFN,GMPSTAT,GMPREV,GMPROV,GMPVIEW,GMPIDX) Q 0
 D BUILDLST(.RETURN,.PLIST)
 Q 1
 ;
GETPLIST(RETURN,GMPDFN,GMPSTAT,GMPREV,GMPROV,GMPVIEW,GMPIDX) ; lists problem ifn's
 N TOTAL
 I '+$G(GMPDFN) D ERRX^GMPLAPIE(.RETURN,"INVPARAM","GMPDFN") Q 0
 S GMPSTAT=$S($G(GMPSTAT)'="":GMPSTAT,1:"A")
 S GMPREV=+$G(GMPREV)
 S GMPROV=+$G(GMPROV)
 S GMPVIEW=$G(GMPVIEW)
 S GMPIDX=+$G(GMPIDX)
 D GETPLIST^GMPLDAL(.RETURN,.TOTAL,GMPDFN,GMPSTAT,GMPREV,GMPROV,GMPVIEW,GMPIDX)
 S RETURN=TOTAL
 Q 1
 ;
BUILDLST(RETURN,GMPLIST) ; Same as LIST but returns only problems passed in GMPLIST
 N I,GMPL,IFN,INACT,ST,ICD,ONSET,LASTMOD,SC,SP,LOC,LT,PROV,SERV
 N PRIO,HASCMT,DTREC,AO,IR,ENV,HNC,MST,CV,SHD,SCCOND,TOTAL,X
 F I=1:1:GMPLIST(0) D
 . S INACT=""
 . S IFN=+GMPLIST(I)
 . Q:'$$DETAIL^GMPLDAL(IFN,.GMPL)
 . S ST=GMPL(.12)
 . I +ORICD186 D
 . . S ICD=$$CODEC^ICDCODE(+GMPL(.01))
 . . I '+$$STATCHK^ICDAPIU(ICD,DT) S INACT="#"
 . E  D
 . . S ICD=$$ICD9NAME^GMPLEXT(GMPL(.01))
 . S ONSET=GMPL(.13)
 . S LASTMOD=GMPL(.03)
 . S SC=$S(+GMPL(1.10):"SC",GMPL(1.10)=0:"NSC",1:"")
 . S SP=""
 . F X=1.11,1.12,1.13 S:GMPL(X) SP=SP_$S(X=1.11:"A",X=1.12:"I",1:"P")
 . S LOC=GMPL(1.08)
 . S LT=""
 . I LOC'="" S LT=$$LOCTYPE^GMPLEXT(LOC),LOC=LOC_";"_$$CLINNAME^GMPLEXT(LOC)
 . S PROV=GMPL(1.05) ; responsible provider
 . I PROV'="" S PROV=PROV_";"_$$PROVNAME^GMPLEXT(PROV)
 . S SERV=GMPL(1.06)
 . I SERV=0 S SERV="" ; not sure how it gets set to 0, but need consistency in GUI
 . I SERV'="" S SERV=SERV_";"_$$SVCNAME^GMPLEXT(SERV)
 . S PRIO=GMPL(1.14)
 . S HASCMT=($D(^AUPNPROB(IFN,11,0))>0)
 . S DTREC=GMPL(1.09)
 . S AO=$S(+GMPL(1.11):"/AO",1:"")
 . S IR=$S(+GMPL(1.12):"/IR",1:"")
 . S ENV=$S(+GMPL(1.13):"/EC",1:"")
 . S HNC=$S(+GMPL(1.15):"/HNC",1:"")
 . S MST=$S(+GMPL(1.16):"/MST",1:"")
 . S CV=$S(+GMPL(1.17):"/CV",1:"")
 . S SHD=$S(+GMPL(1.18):"/SHD",1:"")
 . S SCCOND=SC_AO_IR_ENV_HNC_MST_CV_SHD
 . S RETURN(I)=IFN_U_ST_U_$$PROBTEXT^GMPLX(IFN)_U_ICD_U_ONSET
 . S RETURN(I)=RETURN(I)_U_LASTMOD_U_SC_U_SP_U_GMPL(1.02)
 . S RETURN(I)=RETURN(I)_U_LOC_U_LT_U_PROV_U_SERV_U_PRIO_U_HASCMT_U_DTREC_U_SCCOND_U_INACT
 S RETURN(0)=GMPLIST(0)
 S RETURN=GMPLIST
 Q
 ;
