DGPTDAL1 ;RGI/VSL - PTF DAL; 11/07/2012
 ;;5.3;Registration;**260003**;
GETPTFCO(DATA,PFN,FLDS) ; Get PTF close out
 N TMP,ERR
 I '$D(FLDS) S FLDS="*"
 D GETS^DIQ(45.84,PFN,FLDS,"IE","TMP","ERR")
 I $D(ERR) S DATA=0 M DATA=ERR Q
 S DATA=1 M DATA=TMP(45.84,PFN_",")
 Q
 ;
