DGPTAPI1 ;RGI/VSL - PTF API; 1/10/2013
 ;;5.3;Registration;**260003**;
GETPTFCO(RETURN,PFN) ; Get PTF close out
 N IND,NAME,FLDS,NAMES,MVT
 S FLDS=".01;2;3;4;5;6;"
 S NAMES="PTF;CODATE;COBY;RELDATE;RELBY;DRG"
 D GETPTFCO^DGPTDAL1(.RETURN,PFN,FLDS)
 D BUILD^DGPMAPI8(.RETURN,.MVT,FLDS,NAMES)
 S RETURN=1
 Q 1
