SDD0 ;SF/GFT,ALB/BOK,JSH,LDB - REMAP A CLINIC ;8/7/13
 ;;5.3;Scheduling;**167,401,529,260003**;Aug 13, 1993;Build 3
SETX ;
 S %=$$REMAP^SDAVAPI(.RET,SC,SDBD,SDED)
 F IN=0:0 S IN=$O(RET(IN)) Q:'IN  D PRNT($P(RET(IN,"CLINIC"),U,2),RET(IN,"DATE"),RET(IN,"MSG"))
 Q
PRNT(SDNM,DATE,MSG) ;
 N DAY,Y
 S DAY=$P("SUN^MON^TUES^WEDNES^THURS^FRI^SATUR",U,$$DOW^XLFDT(DATE,1)+1)
 U IO S YP=YP+1 D:YP>(IOSL-4) ESC^SDD W !,$E(SDNM,1,25),?27,$E(DAY,1,3)_" " S Y=DATE D DT^DIO2 W ?45,MSG
 Q
 ;
ESC S SDU=0 I $E(IOST,1,2)="C-" W *7 R ESC:DTIME S:U=ESC SDU=1
