SDMAPI ;MAKE APPOINTMENT API; 05/28/2012  11:46 AM
 ;;;Scheduling;;05/28/2012;
BLDLST(RETURN,LST) ; Build simple list.
 N DL,IN
 S RETURN=0
 S RETURN(0)=LST("DILIST",0)
 S DL="DILIST"
 F IN=1:1:$P(RETURN(0),U,1) D
 . S RETURN(IN)=""
 . S RETURN(IN,"ID")=LST(DL,2,IN)
 . S RETURN(IN,"NAME")=LST(DL,"ID",IN,".01")
 S RETURN=1
 Q 1
 ;
