SDMAPI5 ;RGI/VSL - APPOINTMENT API; 2/04/2013
 ;;5.3;scheduling;**260003**;08/13/93;
CHKTYPE(RETURN,DFN,TYPE) ; Check appointment type
 N PAT,ERR,ELIG,ATYP
 K RETURN S RETURN=0
 I '+$G(TYPE) D ERRX^SDAPIE(.RETURN,"INVPARAM","TYPE") Q 0
 I '$$TYPEXST^SDMDAL3(+TYPE) D ERRX^SDAPIE(.RETURN,"TYPNFND") Q 0
 D GETPAT^SDMDAL3(.PAT,+DFN,1) S ERR=0
 I PAT(.301)=""!('+PAT(.361)),+TYPE=11 S ERR=1
 I PAT(.301)="N",(+PAT(.302)>0)!(PAT(.361)=1)!(PAT(.361)=3),+TYPE=11 S ERR=1
 I PAT(.301)="Y",+PAT(.302)<50,PAT(.361)'=3,+TYPE=11 S ERR=1
 I PAT(.301)="Y",+PAT(.302)>49,PAT(.361)'=1,+TYPE=11 S ERR=1
 I ERR D ERRX^SDAPIE(.RETURN,"TYPINVSC") Q 0
 D GETELIG^SDMDAL2(.ELIG,PAT(.361),1)
 D GETAPPT^SDMDAL2(.ATYP,+TYPE,1)
 I '$G(ATYP(3)),$S($G(ELIG(4))["Y":1,1:$G(ATYP(5))),$S('$G(ATYP(6)):1,$D(PAT(361,+ATYP(6))):1,+PAT(.361)=ATYP(6):1,1:0) S RETURN=1
 I RETURN=0 D ERRX^SDAPIE(.RETURN,"TYPINVD") Q 0
 S RETURN=1
 Q 1
 ;
CHKSTYP(RETURN,TYPE,STYP) ; Check appointment subtype
 N LST,I,DL
 S DL="DILIST"
 K RETURN S RETURN=0
 I +$G(STYP)=0 S RETURN=1 Q 1
 D LSTASTYP^SDMDAL2(.LST,,,,+$G(TYPE))
 F I=0:0 S I=$O(LST(DL,2,I)) Q:I=""  D
 . I LST(DL,2,I)=+STYP,LST(DL,"ID",I,.03)="YES" S RETURN=1
 I 'RETURN D ERRX^SDAPIE(.RETURN,"STYPNFND") Q 0
 S RETURN=1
 Q 1
 ;
LSTASTYP(RETURN,SEARCH,START,NUMBER,TYPE) ; List appointment subtypes
 N LST,FLDS
 M LST=RETURN
 D LSTASTYP^SDMDAL2(.LST,$$UP^XLFSTR($G(SEARCH)),.START,$G(NUMBER),+$G(TYPE))
 K RETURN
 S FLDS(.02)="NAME",FLDS(.03)="STATUS"
 D BLDLST^SDMAPI(.RETURN,.LST,.FLDS)
 S RETURN=1
 Q RETURN
 ;
