SDMLST ;RGI/CBR - Lists Utils; 07/25/2012
 ;;5.3;scheduling;**260003**;08/13/93
LSTCLNS(RETURN,SEARCH,START,NUMBER) ; Lists clinics
 S %=$$LSTCLNS^SDMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTPATS(RETURN,SEARCH,START,NUMBER) ; Lists patients
 S %=$$LSTPATS^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTCRSNS(RETURN,SEARCH,START,NUMBER) ; Lists cancellation reasons
 S %=$$LSTCRSNS^SDMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTETNS(RETURN,SEARCH,START,NUMBER) ; Lists ethnics
 S %=$$LSTETNS^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTRACES(RETURN,SEARCH,START,NUMBER) ; Lists races
 S %=$$LSTRACES^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
GETPRES(RETURN,SEARCH) ; Lists patient races
 S %=$$GETPRES^SDMAPI3(.RETURN,.DFN)
 Q
