SDPROAPI ;RGI/VSL - SDAM APPOINTMENT EVENTS API ; 7/22/13
 ;;5.3;Scheduling;**260003**;;
DELALL() ; Remove all protocols
 N SDAM,PROTS
 S PROTS=$$GETALL()
 S SDAM="SDAM APPOINTMENT EVENTS"
 F IN=1:1:999 S PROT=$P(PROTS,"^",IN) Q:PROT=""  D
 . S %=$$DELETE^XPDPROT(SDAM,PROT)
 Q
ADDALL() ; Add all protocols
 N SDAM,PROTS
 S PROTS=$$GETALL()
 S SDAM="SDAM APPOINTMENT EVENTS"
 S SEQS="^^4^8^^^^^^^^^^99^"
 F IN=1:1:999 S PROT=$P(PROTS,"^",IN) Q:PROT=""  D
 . S %=$$ADD^XPDPROT(SDAM,PROT,,$P(SEQS,"^",IN))
 Q
GETALL() ;
 N PROTS
 S PROTS="ORU PATIENT MOVMT^DG MEANS TEST REQUIRED^IBACM OP LINK^DVBA C&P SCHD EVENT^"
 S PROTS=PROTS_"PXK SDAM TO V-FILES^VAFH HL7 OUTPATIENT CAPTURE^VAFC HL7 OUTPATIENT CAPTURE^"
 S PROTS=PROTS_"DGEN SD ENROLL PATIENT^IVM SEND FINANCIAL QUERY^RG ADT OUTPATIENT ENCOUNTER DRIVER^"
 S PROTS=PROTS_"EAS UE SCHED EVENT^SDAM APPT TYPE VALIDATION^SDAM PFSS EVENT^EDP CHECK-IN^"
 Q PROTS
